<?php
$title = 'Add new tea';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('tea', array('action' => 'add')));
$form->setAttribute('role', 'form');
$form->prepare();

foreach ($form as $element) :?>
	<div class="form-group">
		<?php 
			if ($element->getOption('required')) { $req = 'required'; }
			$type = $element->getAttribute('type');
			$name = $element->getAttribute('name'); 
			$label = $element->getLabel();
		?>
		<?php if ($name == 'id') { ?>
			<div class="hidden"><?php echo $this->formElement($element); ?></div>
		<?php } else if ($name == 'submit') { ?>
			<input class='btn' name='submit' type='submit' value='Add'>
		<?php } else if ($label != '') { ?>
			<label class="control-label"><?php echo $label ?></label>
			<input class='form-control' name='<?php echo $name ?>' type='<?php echo $type ?>'>
		<?php } ?> 
	</div>
<?php 
endforeach;
echo $this->form()->closeTag();

/*
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('brand'));
 echo $this->formRow($form->get('serving'));
 echo $this->formRow($form->get('servings'));
 echo $this->formRow($form->get('ingredients'));
 echo $this->formRow($form->get('description'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 */
?>