<?php

$title = 'Delete tea';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($tea->name); ?>' of
    '<?php echo $this->escapeHtml($tea->brand); ?>'?
</p>
<?php
$url = $this->url('tea', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $tea->id; ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn" name="del" value="No" />
</div>
</form>