<?php
$title = 'Edit tea';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'tea',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
foreach ($form as $element) :?>
	<div class="form-group">
		<?php 
			if ($element->getOption('required')) { $req = 'required'; }
			$type = $element->getAttribute('type');
			$name = $element->getAttribute('name'); 
			$label = $element->getLabel();
		?>
		<?php if ($name == 'id') { ?>
			<div class="hidden"><?php echo $this->formElement($element); ?></div>
		<?php } else if ($name == 'submit') { ?>
			<input type='submit' class='btn btn-default' name='submit' value="Submit">
			<a type='button' class='btn btn-danger' href=
				'<?php echo $this->url('tea', array('action'=>'delete', 'id'=>$this->id,)); ?>'>Delete</a>
		<?php } else if ($label != '') { ?>
			<label class="control-label"><?php echo $label ?></label>
			<input class='form-control' name='<?php echo $name ?>' type='<?php echo $type ?>'
				value='<?php echo $element->getValue() ?>'>
		<?php } ?> 
	</div>
<?php 
endforeach;
?>